import{S as c,i as u}from"./assets/vendor-f33cd494.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const m=t=>`
   <li class="gallery-card">
    <a class="gallery-card-link" href="${t.largeImageURL}">
    <img class="gallery-img" src="${t.largeImageURL}" alt="${t.tags}"
    preview="${t.webformatURL}"/> 
    <p>Likes=${t.likes} Views=${t.views} Comments=${t.comments} Downloads=${t.downloads}</p>
    </a>
  </li>
  `,h="https://pixabay.com/api/",d=t=>{const s=new URLSearchParams({key:"45517273-e9991eeaabacaef63628b20e0",q:t,image_type:"photo",orientation:"horizontal",safesearch:"true"});return fetch(`${h}?${s}`).then(o=>{if(!o.ok)throw new Error(o.status);return o.json()})};let p=new c(".gallery a",{navText:["<",">"],captionPosition:"bottom",captionsData:"alt",captionDelay:250,enableKeyboard:!0,closeText:"x",showCounter:!0,overlayOpacity:.8});const n=document.querySelector(".js-search-form"),i=document.querySelector(".js-gallery"),y=t=>{t.preventDefault();const s=n.elements.user_query.value;d(s).then(o=>{if(o.hits.length===0){u.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),i.innerHTML="",n.reset();return}const a=o.hits.map(e=>m(e)).join("");i.innerHTML=a,p.refresh()}).catch(o=>{console.log(o)})};n.addEventListener("submit",y);
//# sourceMappingURL=commonHelpers.js.map
